#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := BH1750.cpp BH1750_Average.cpp lightmeter.cpp

# header files in this project
HEADERS := BH1750.hpp BH1750_Average.hpp lightmeter.hpp

# other places to look for files for this project
SEARCH  := ../BH1750/

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ../
include $(RELATIVE)/Makefile.due
